DROP TABLE IF EXISTS mahasiswa;
DROP TABLE IF EXISTS post;

CREATE TABLE mahasiswa (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    nama TEXT NOT NULL,
    nim TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL
);

CREATE TABLE post (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    id_pemilik INTEGER NOT NULL,
    dibuat TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    judul TEXT NOT NULL,
    isi TEXT NOT NULL,
    FOREIGN KEY (id_pemilik) REFERENCES mahasiswa (id)
);